name: Build and Publish Release

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run compile

      - name: Install latest version of @vscode/vsce
        run: npm install -g @vscode/vsce@latest

      - name: Package VSIX
        run: npx vsce package

      - name: Get package version
        id: get_version
        run: echo "$(node -p "require('./package.json').version")"

      - name: Set version output
        run: echo "VERSION=${{ steps.get_version.outputs.stdout }}" >> $GITHUB_ENV

      - name: List Files
        run: ls

      - name: Get package version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: GH Release Action
        uses: zcubbs/gh-release-action@v1.0.6
        with:
          major: ${{ env.VERSION_MAJOR }}
          minor: ${{ env.VERSION_MINOR }}
          patch: ${{ env.VERSION_PATCH }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: sagemath-enhanced-${{ env.VERSION }}.vsix
